sugarbeet:
  campaign_date: 2001-1-15
  crop_name: sugarbeet
  variety_name: Sugarbeet_601
  crop_start_date: 2001-3-15
  crop_end_type: maturity
winterwheat:
  campaign_date: 1999-8-20
  crop_name: winterwheat
  variety_name: Julius
  crop_start_date: 1999-10-3
  crop_end_type: maturity
potato:
  campaign_date: 1999-3-1
  crop_name: potato
  variety_name: Innovator
  crop_start_date: 1999-5-1
  crop_end_type: maturity
