field-1:
  soil_lon: 5.54
  soil_lat: 52.5
  crop: sugarbeet
field-2:
  soil_lon: 5.54
  soil_lat: 52.49
  crop: winterwheat
field-3:
  soil_lon: 5.55
  soil_lat: 52.5
  crop: potato
field-4:
  soil_lon: 5.56
  soil_lat: 52.5
  crop: sugarbeet
field-5:
  soil_lon: 5.54
  soil_lat: 52.49
  crop: winterwheat
field-6:
  soil_lon: 5.54
  soil_lat: 52.49
  crop: potato