scenarios:
  sugarbeet_field1:
    crop_name: sugarbeet
    variety_name: Sugarbeet_602
    year: 2001
    sowing_date: [2001, 4, 15]
    harvest_date: [2001, 9, 30]
    start_type: sowing
    soil_lon: 5.54
    soil_lat: 52.49
  winterwheat_field2:
    crop_name: winterwheat
    variety_name: Arminda
    year: 2000
    sowing_date: [1999, 10, 3]
    harvest_date: [2000, 8, 20]
    start_type: sowing
    soil_lon: 23.88
    soil_lat: 55.13