- 1999-10-01:
    CropCalendar:
        crop_name: winterwheat
        variety_name: Arminda
        crop_start_date: 1999-10-03
        crop_start_type: sowing
        crop_end_date:
        crop_end_type: maturity
    TimedEvents: null
    StateEvents: null